// =============================================================================
// Zephyr Test Case : SCRUM-T62
// Title            : Verify User Login to OrangeHRM Application with the maximum number of records
// Priority         : Normal
// Labels           : boundary, edge-case, performance, bva-volume, scrum-6
// Steps from Zephyr:
//   1. [Pre-condition] Identify the system's maximum record limit for User Login to OrangeHRM Application (from documentation or config).
//   2. Create records up to near-maximum capacity (or use existing data if already near limit).
//   3. Attempt to perform User Login to OrangeHRM Application at the near-maximum threshold and verify normal behaviour.
//   4. Attempt to perform User Login to OrangeHRM Application at the exact maximum limit. Observe and document the response.
//   5. Attempt to perform User Login to OrangeHRM Application one record beyond the maximum limit.
//   6. Verify the system displays a meaningful limit-exceeded error message (not a crash or 500 error).
//   7. Verify system performance: page load, search, and save operations remain within acceptable time (&lt; 5 seconds).
//   8. Verify the system does not create partial records or corrupt existing data at capacity boundary.
// =============================================================================
// Generated by  : scripts/generate-playwright.js
// Application   : OrangeHRM — https://opensource-demo.orangehrmlive.com
// Module        : PIM → Add Employee
// Credentials   : Admin / admin123
// Fixtures      : base.fixture.js (POM + Applitools Eyes + ScreenshotHelper)
// =============================================================================
'use strict';
const { test, expect }                = require('../fixtures/base.fixture');
const { CREDENTIALS, TEST_EMPLOYEE } = require('../data/testData');

test.describe('SCRUM-T62 | Verify User Login to OrangeHRM Application with the maximum number of records', () => {

  test('Verify User Login to OrangeHRM Application with the maximum number of records', async ({ page, loginPage, addEmployeePage, employeeListPage, sh, eyes, uniqueSuffix }, testInfo) => {

    await sh.step('Log in as HR Admin', async () => {
      await loginPage.login(CREDENTIALS.admin.username, CREDENTIALS.admin.password);
    });

    await sh.step('Test minimum boundary — single character names (A, B)', async () => {
      await addEmployeePage.navigate();
      await addEmployeePage.fillEmployee({ firstName: 'A', lastName: 'B' });
      await addEmployeePage.save();
      await expect(page).toHaveURL(/viewPersonalDetails|addEmployee/, { timeout: 10000 });
    });

    await sh.step('Test maximum boundary — 50-character names', async () => {
      await addEmployeePage.navigate();
      await addEmployeePage.fillEmployee({
        firstName: 'A'.repeat(50),
        lastName:  'B'.repeat(50)
      });
      await addEmployeePage.save();
      await page.waitForLoadState('networkidle');
      expect(page.url()).not.toMatch(/error|exception/i);
    });

    await sh.step('Test over-maximum boundary — 101-character names', async () => {
      await addEmployeePage.navigate();
      await addEmployeePage.fillEmployee({
        firstName: 'X'.repeat(101),
        lastName:  'Y'.repeat(101)
      });
      await addEmployeePage.save();
      await page.waitForLoadState('networkidle');
      expect(page.url()).not.toMatch(/error|exception/i);
    });
  });

});
