// =============================================================================
// Zephyr Test Case : SCRUM-T38
// Title            : Verify User Login to OrangeHRM Application rejects invalid input data
// Priority         : Normal
// Labels           : validation, negative, invalid-data, ep-invalid, security-eg
// Steps from Zephyr:
//   1. [Pre-condition] User is logged in as Admin. Navigate to User Login to OrangeHRM Application form.
//   2. Enter numeric-only value &quot;12345&quot; in the First Name field.
//   3. Enter special characters &quot;!@#$%^&amp;*&quot; in the Last Name field.
//   4. Click Save / Submit and observe any validation errors shown.
//   5. Clear the fields and enter HTML injection attempt &quot;&quot; in First Name.
//   6. Click Save / Submit and verify the system handles this without executing script.
//   7. Clear the fields and enter a value with spaces &quot;John Doe Smith&quot; in a username-type field.
//   8. Submit and observe system response (expect validation error or sanitised output).
//   9. Verify no system crash, 500 error, or unhandled exception occurs at any point.
//   10. [Post-condition] Confirm no invalid records were persisted in the database.
// =============================================================================
// Generated by  : scripts/generate-playwright.js
// Application   : OrangeHRM — https://opensource-demo.orangehrmlive.com
// Module        : PIM → Add Employee
// Credentials   : Admin / admin123
// =============================================================================
'use strict';
const { test, expect }           = require('../fixtures/eyes.fixture');
const { LoginPage }              = require('../pages/LoginPage');
const { AddEmployeePage }        = require('../pages/AddEmployeePage');
const { EmployeeListPage }       = require('../pages/EmployeeListPage');
const { ScreenshotHelper }       = require('../helpers/screenshot.helper');
const { CREDENTIALS, TEST_EMPLOYEE } = require('../data/testData');

test.describe('SCRUM-T38 | Verify User Login to OrangeHRM Application rejects invalid input data', () => {

  test.beforeEach(async ({ page }) => {
    // Start each test with a clean session
    await page.context().clearCookies();
  });

  test('Verify User Login to OrangeHRM Application rejects invalid input data', async ({ page, eyes }, testInfo) => {
    const sh              = new ScreenshotHelper(page, testInfo, eyes);
    const loginPage       = new LoginPage(page);
    const addEmployeePage = new AddEmployeePage(page);

    await sh.step('Log in and open Add Employee form', async () => {
      await loginPage.login(CREDENTIALS.admin.username, CREDENTIALS.admin.password);
      await addEmployeePage.navigate();
    });

    await sh.step('Enter invalid data — numerics and symbols in name fields', async () => {
      await addEmployeePage.fillEmployee({ firstName: '12345', lastName: '!@#$%' });
    });

    await sh.step('Submit the form with invalid data', async () => {
      await addEmployeePage.save();
    });

    await sh.step('Verify no crash — system shows validation or stays on form', async () => {
      await page.waitForLoadState('networkidle');
      expect(page.url()).not.toMatch(/error|exception/i);
    });
  });

});
