// =============================================================================
// Zephyr Test Case : SCRUM-T40
// Title            : Verify duplicate User Login to OrangeHRM Application is prevented
// Priority         : Normal
// Labels           : validation, negative, duplicate, error-guessing
// Steps from Zephyr:
//   1. [Pre-condition] User is logged in as Admin.
//   2. Perform a successful User Login to OrangeHRM Application: Enter First Name &quot;DupeTest&quot;, Last Name &quot;DupeUser&quot;, save the record.
//   3. Note the generated employee ID or unique identifier: &quot;DUP001&quot;.
//   4. Navigate back to the User Login to OrangeHRM Application form.
//   5. Attempt to create a second record with the exact same unique identifier &quot;DUP001&quot;.
//   6. Click Save / Submit.
//   7. Observe the system response for the duplicate attempt.
//   8. Verify a duplicate-specific error message is displayed (e.g. &quot;Employee ID already exists&quot;).
//   9. Verify only one record exists in the system for the tested identifier.
//   10. [Cleanup] Delete the test record created in step 2 if the system allows.
// =============================================================================
// Generated by  : scripts/generate-playwright.js
// Application   : OrangeHRM — https://opensource-demo.orangehrmlive.com
// Module        : PIM → Add Employee
// Credentials   : Admin / admin123
// =============================================================================
'use strict';
const { test, expect }           = require('@playwright/test');
const { LoginPage }              = require('../pages/LoginPage');
const { AddEmployeePage }        = require('../pages/AddEmployeePage');
const { EmployeeListPage }       = require('../pages/EmployeeListPage');
const { ScreenshotHelper }       = require('../helpers/screenshot.helper');
const { CREDENTIALS, TEST_EMPLOYEE } = require('../data/testData');

test.describe('SCRUM-T40 | Verify duplicate User Login to OrangeHRM Application is prevented', () => {

  test.beforeEach(async ({ page }) => {
    // Start each test with a clean session
    await page.context().clearCookies();
  });

  test('Verify duplicate User Login to OrangeHRM Application is prevented', async ({ page }, testInfo) => {
    const sh              = new ScreenshotHelper(page, testInfo);
    const loginPage       = new LoginPage(page);
    const addEmployeePage = new AddEmployeePage(page);

    await sh.step('Log in as HR Admin', async () => {
      await loginPage.login(CREDENTIALS.admin.username, CREDENTIALS.admin.password);
    });

    await sh.step('Create first employee with Employee ID DUP-TEST-001', async () => {
      await addEmployeePage.navigate();
      await addEmployeePage.fillEmployee({ firstName: 'DupFirst', lastName: 'DupLast' });
      await addEmployeePage.setEmployeeId('DUP-TEST-001');
      await addEmployeePage.save();
      await page.waitForLoadState('networkidle');
    });

    await sh.step('Attempt second creation with same Employee ID DUP-TEST-001', async () => {
      await addEmployeePage.navigate();
      await addEmployeePage.fillEmployee({ firstName: 'DupFirst2', lastName: 'DupLast2' });
      await addEmployeePage.setEmployeeId('DUP-TEST-001');
      await addEmployeePage.save();
      await page.waitForLoadState('networkidle');
    });

    await sh.step('Verify system blocks or warns — no crash on duplicate', async () => {
      expect(page.url()).not.toMatch(/error|exception/i);
    });
  });

});
