// =============================================================================
// Zephyr Test Case : SCRUM-T73
// Title            : Verify browser back/forward navigation during User Login to OrangeHRM Application
// Priority         : Normal
// Labels           : edge-case, state-transition, scrum-6, dynamic-generated, browser-navigation
// Steps from Zephyr:
//   1. [Given] [Pre-condition] User is logged in as Admin. Navigate to User Login to OrangeHRM Application form.
//   2. [When] Fill in all required fields with valid data but do NOT submit.
//   3. [When] Click the browser Back button. Then click browser Forward button.
//   4. [Then] Verify the form reloads without errors (data may or may not be preserved).
//   5. [Then] Fill the form again and click Submit. Verify success.
//   6. [When] Immediately click the browser Back button after successful submission.
//   7. [Then] Verify the system does NOT re-submit the form (no duplicate record created).
//   8. [Then] Click browser Forward button and verify the confirmation/list page loads correctly.
// =============================================================================
// Generated by  : scripts/generate-playwright.js
// Application   : OrangeHRM — https://opensource-demo.orangehrmlive.com
// Module        : PIM → Add Employee
// Credentials   : Admin / admin123
// Fixtures      : base.fixture.js (POM + Applitools Eyes + ScreenshotHelper)
// =============================================================================
'use strict';
const { test, expect }                = require('../fixtures/base.fixture');
const { CREDENTIALS, TEST_EMPLOYEE } = require('../data/testData');

test.describe('SCRUM-T73 | Verify browser back/forward navigation during User Login to OrangeHRM Application', () => {

  test('Verify browser back/forward navigation during User Login to OrangeHRM Application', async ({ page, loginPage, addEmployeePage, employeeListPage, sh, eyes, uniqueSuffix }, testInfo) => {

    await sh.step('Log in as HR Admin', async () => {
      await loginPage.login(CREDENTIALS.admin.username, CREDENTIALS.admin.password);
    });

    await sh.step('Navigate to Add Employee form', async () => {
      await addEmployeePage.navigate();
    });

    await sh.step("1. [Given] [Pre-condition] User is logged in as Admin. Navigate to User Login to OrangeHRM Application form.", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step("2. [When] Fill in all required fields with valid data but do NOT submit.", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step("3. [When] Click the browser Back button. Then click browser Forward button.", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step("4. [Then] Verify the form reloads without errors (data may or may not be preserved).", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step("5. [Then] Fill the form again and click Submit. Verify success.", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step("6. [When] Immediately click the browser Back button after successful submission.", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step("7. [Then] Verify the system does NOT re-submit the form (no duplicate record created).", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step("8. [Then] Click browser Forward button and verify the confirmation/list page loads correctly.", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step('Verify no error condition after all steps', async () => {
      await page.waitForLoadState('networkidle');
      expect(page.url()).not.toMatch(/error|exception/i);
    });
  });

});
