// =============================================================================
// Zephyr Test Case : SCRUM-T43
// Title            : Verify cancel or discard action during User Login to OrangeHRM Application
// Priority         : Normal
// Labels           : negative, cancel, data-integrity, state-transition
// Steps from Zephyr:
//   1. {"inline":{"description":null,"testData":null,"expectedResult":null,"customFields":{},"reflectRef":null},"testCase":null}
// =============================================================================
// Generated by  : scripts/generate-playwright.js
// Application   : OrangeHRM — https://opensource-demo.orangehrmlive.com
// Module        : PIM → Add Employee
// Credentials   : Admin / admin123
// =============================================================================
'use strict';
const { test, expect }           = require('../fixtures/eyes.fixture');
const { LoginPage }              = require('../pages/LoginPage');
const { AddEmployeePage }        = require('../pages/AddEmployeePage');
const { EmployeeListPage }       = require('../pages/EmployeeListPage');
const { ScreenshotHelper }       = require('../helpers/screenshot.helper');
const { CREDENTIALS, TEST_EMPLOYEE } = require('../data/testData');

test.describe('SCRUM-T43 | Verify cancel or discard action during User Login to OrangeHRM Application', () => {

  test.beforeEach(async ({ page }) => {
    // Start each test with a clean session
    await page.context().clearCookies();
  });

  test('Verify cancel or discard action during User Login to OrangeHRM Application', async ({ page, eyes }, testInfo) => {
    const sh               = new ScreenshotHelper(page, testInfo, eyes);
    const loginPage        = new LoginPage(page);
    const addEmployeePage  = new AddEmployeePage(page);
    const employeeListPage = new EmployeeListPage(page);

    await sh.step('Log in as HR Admin', async () => {
      await loginPage.login(CREDENTIALS.admin.username, CREDENTIALS.admin.password);
    });

    await sh.step('Navigate to Add Employee and partially fill the form', async () => {
      await addEmployeePage.navigate();
      await addEmployeePage.fillEmployee({ firstName: 'CancelTest', lastName: 'Discard' });
    });

    await sh.step('Cancel — navigate away without saving', async () => {
      await addEmployeePage.cancel();
      await page.waitForLoadState('networkidle');
    });

    await sh.step('Verify no redirect to Personal Details occurred', async () => {
      expect(page.url()).not.toMatch(/viewPersonalDetails/);
    });

    await sh.step('Search Employee List — cancelled record should not exist', async () => {
      await employeeListPage.searchEmployee('CancelTest');
      await page.waitForLoadState('networkidle');
      expect(page.url()).not.toMatch(/error|exception/i);
    });
  });

});
