// =============================================================================
// Zephyr Test Case : SCRUM-T54
// Title            : Verify mandatory fields are enforced for User Login to OrangeHRM Application
// Priority         : Normal
// Labels           : validation, negative, required-fields, ep-empty, scrum-6
// Steps from Zephyr:
//   1. [Pre-condition] User is logged in as Admin.
//   2. Navigate to the User Login to OrangeHRM Application page or form.
//   3. Leave the First Name field completely empty (do not enter any value).
//   4. Leave the Last Name field completely empty (do not enter any value).
//   5. Leave any other mandatory fields empty.
//   6. Click the Save / Submit button without filling any required fields.
//   7. Observe all inline validation messages that appear below each empty field.
//   8. Verify the form does NOT submit (URL remains on the form page).
//   9. Verify the First Name field shows an error message (e.g. &quot;Required&quot;).
//   10. Verify the Last Name field shows an error message (e.g. &quot;Required&quot;).
// =============================================================================
// Generated by  : scripts/generate-playwright.js
// Application   : OrangeHRM — https://opensource-demo.orangehrmlive.com
// Module        : PIM → Add Employee
// Credentials   : Admin / admin123
// Fixtures      : base.fixture.js (POM + Applitools Eyes + ScreenshotHelper)
// =============================================================================
'use strict';
const { test, expect }                = require('../fixtures/base.fixture');
const { CREDENTIALS, TEST_EMPLOYEE } = require('../data/testData');

test.describe('SCRUM-T54 | Verify mandatory fields are enforced for User Login to OrangeHRM Application', () => {

  test('Verify mandatory fields are enforced for User Login to OrangeHRM Application', async ({ page, loginPage, addEmployeePage, employeeListPage, sh, eyes, uniqueSuffix }, testInfo) => {

    await sh.step('Log in as HR Admin', async () => {
      await loginPage.login(CREDENTIALS.admin.username, CREDENTIALS.admin.password);
    });

    await sh.step('Open Add Employee form', async () => {
      await addEmployeePage.navigate();
    });

    await sh.step('Clear all required fields (First Name, Last Name)', async () => {
      await addEmployeePage.firstNameInput.clear();
      await addEmployeePage.lastNameInput.clear();
    });

    await sh.step('Attempt to submit with empty required fields', async () => {
      await addEmployeePage.save();
    });

    await sh.step('Verify inline validation error messages appear', async () => {
      await expect(addEmployeePage.validationErrors.first()).toBeVisible({ timeout: 5000 });
      const errorCount = await addEmployeePage.validationErrors.count();
      expect(errorCount).toBeGreaterThanOrEqual(1);
      await expect(page).not.toHaveURL(/viewPersonalDetails/);
    });
  });

});
