// =============================================================================
// Zephyr Test Case : SCRUM-T36
// Title            : Verify successful User Login to OrangeHRM Application with valid inputs
// Priority         : Normal
// Labels           : happy-path, smoke, ep-valid
// Steps from Zephyr:
//   1. [Pre-condition] User is logged out. Browser is open at the application URL.
//   2. Navigate to the application login page and log in with valid admin credentials (Username: Admin, Password: admin123).
//   3. Navigate to the User Login to OrangeHRM Application page or form via the main navigation menu.
//   4. Verify the form/page loads completely with all fields visible.
//   5. Fill in First Name field with valid test data: &quot;AutoTest&quot; (alphabetic, within 1&ndash;50 char limit).
//   6. Fill in Last Name field with valid test data: &quot;Employee&quot; (alphabetic, within 1&ndash;50 char limit).
//   7. Fill in any other required fields with valid test data as per test data table.
//   8. Click the Save / Submit button to trigger the action.
//   9. Wait for the system response (success message or redirect).
//   10. Verify a success confirmation message is displayed (e.g. &quot;Successfully Saved&quot;).
// =============================================================================
// Generated by  : scripts/generate-playwright.js
// Application   : OrangeHRM — https://opensource-demo.orangehrmlive.com
// Module        : PIM → Add Employee
// Credentials   : Admin / admin123
// =============================================================================
'use strict';
const { test, expect }           = require('../fixtures/eyes.fixture');
const { LoginPage }              = require('../pages/LoginPage');
const { AddEmployeePage }        = require('../pages/AddEmployeePage');
const { EmployeeListPage }       = require('../pages/EmployeeListPage');
const { ScreenshotHelper }       = require('../helpers/screenshot.helper');
const { CREDENTIALS, TEST_EMPLOYEE } = require('../data/testData');

test.describe('SCRUM-T36 | Verify successful User Login to OrangeHRM Application with valid inputs', () => {

  test.beforeEach(async ({ page }) => {
    // Start each test with a clean session
    await page.context().clearCookies();
  });

  test('Verify successful User Login to OrangeHRM Application with valid inputs', async ({ page, eyes }, testInfo) => {
    const sh              = new ScreenshotHelper(page, testInfo, eyes);
    const loginPage       = new LoginPage(page);
    const addEmployeePage = new AddEmployeePage(page);

    await sh.step('Open Login Page', async () => {
      await loginPage.goto();
    });

    await sh.step('Enter credentials and log in as HR Admin', async () => {
      await loginPage.usernameInput.fill(CREDENTIALS.admin.username);
      await loginPage.passwordInput.fill(CREDENTIALS.admin.password);
      await loginPage.loginButton.click();
      await page.waitForURL('**/dashboard**', { timeout: 15000 });
    });

    await sh.step('Navigate to PIM — Add Employee form', async () => {
      await addEmployeePage.navigate();
      await expect(page).toHaveURL(/addEmployee/);
    });

    await sh.step('Fill all required fields with valid data', async () => {
      await addEmployeePage.fillEmployee({
        firstName: TEST_EMPLOYEE.firstName,
        lastName:  TEST_EMPLOYEE.lastName
      });
    });

    await sh.step('Submit form and verify redirect to Personal Details', async () => {
      await addEmployeePage.save();
      await expect(page).toHaveURL(/viewPersonalDetails/, { timeout: 15000 });
      await expect(page.locator('h6.oxd-text').first()).toBeVisible();
    });
  });

});
