// =============================================================================
// Zephyr Test Case : SCRUM-T33
// Title            : Verify data is persisted correctly after User Login to OrangeHRM Application
// Priority         : Normal
// Labels           : data-integrity, persistence, regression, state-transition
// Steps from Zephyr:
//   1. [State: Pre-action] Count existing records before test (note the total).
//   2. Navigate to User Login to OrangeHRM Application form. Enter First Name: &quot;PersistTest&quot;, Middle Name: &quot;Verify&quot;, Last Name: &quot;DataCheck&quot;.
//   3. Click Save. Verify success message appears.
//   4. [State: Record Created] Note the assigned employee ID or unique identifier.
//   5. Navigate away from the page to the employee list/dashboard.
//   6. [State: Navigated Away] Return to the employee list and search for &quot;PersistTest&quot;.
//   7. Open the newly created record.
//   8. [State: Retrieved] Verify First Name = &quot;PersistTest&quot; (exact match, including case).
//   9. Verify Middle Name = &quot;Verify&quot; (exact match).
//   10. Verify Last Name = &quot;DataCheck&quot; (exact match).
// =============================================================================
// Generated by  : scripts/generate-playwright.js
// Application   : OrangeHRM — https://opensource-demo.orangehrmlive.com
// Module        : PIM → Add Employee
// Credentials   : Admin / admin123
// =============================================================================
'use strict';
const { test, expect }           = require('@playwright/test');
const { LoginPage }              = require('../pages/LoginPage');
const { AddEmployeePage }        = require('../pages/AddEmployeePage');
const { EmployeeListPage }       = require('../pages/EmployeeListPage');
const { ScreenshotHelper }       = require('../helpers/screenshot.helper');
const { CREDENTIALS, TEST_EMPLOYEE } = require('../data/testData');

test.describe('SCRUM-T33 | Verify data is persisted correctly after User Login to OrangeHRM Application', () => {

  test.beforeEach(async ({ page }) => {
    // Start each test with a clean session
    await page.context().clearCookies();
  });

  test('Verify data is persisted correctly after User Login to OrangeHRM Application', async ({ page }, testInfo) => {
    const sh              = new ScreenshotHelper(page, testInfo);
    const loginPage       = new LoginPage(page);
    const addEmployeePage = new AddEmployeePage(page);

    await sh.step('Log in as HR Admin', async () => {
      await loginPage.login(CREDENTIALS.admin.username, CREDENTIALS.admin.password);
    });

    const uniqueSuffix = String(Date.now()).slice(-5);

    await sh.step('Navigate to Add Employee and fill with known values', async () => {
      await addEmployeePage.navigate();
      await addEmployeePage.fillEmployee({ firstName: 'Persist', lastName: `DC${uniqueSuffix}` });
      await addEmployeePage.setEmployeeId(`DP${uniqueSuffix}`);
    });

    await sh.step('Save the employee record', async () => {
      await addEmployeePage.save();
      await expect(page).toHaveURL(/viewPersonalDetails/, { timeout: 20000 });
    });

    await sh.step('Verify First Name is persisted correctly', async () => {
      await expect(page.locator('input[name="firstName"]'))
        .toHaveValue('Persist', { timeout: 8000 });
    });

    await sh.step('Verify Last Name is persisted correctly', async () => {
      await expect(page.locator('input[name="lastName"]'))
        .toHaveValue(`DC${uniqueSuffix}`, { timeout: 8000 });
    });
  });

});
