// =============================================================================
// Zephyr Test Case : SCRUM-T35
// Title            : Verify role-based access control for User Login to OrangeHRM Application
// Priority         : Normal
// Labels           : security, authorization, rbac, decision-table
// Steps from Zephyr:
//   1. [Pre-condition] Identify all roles relevant to User Login to OrangeHRM Application (Admin, ESS User, Supervisor).
//   2. Log in as a user with the Admin role. Attempt to perform User Login to OrangeHRM Application. Verify the action succeeds.
//   3. Log out. Log in as an ESS User (no admin rights). Navigate to User Login to OrangeHRM Application page.
//   4. Verify the action is blocked &mdash; either the URL redirects, the button is disabled, or an &quot;Access Denied&quot; message shows.
//   5. Log out. Log in as a Supervisor role. Attempt the same action. Verify blocked as per role matrix.
//   6. Access the URL directly without being logged in &mdash; verify redirect to login page.
//   7. [Post-condition] Confirm no unauthorised actions were recorded in the system audit log.
// =============================================================================
// Generated by  : scripts/generate-playwright.js
// Application   : OrangeHRM — https://opensource-demo.orangehrmlive.com
// Module        : PIM → Add Employee
// Credentials   : Admin / admin123
// =============================================================================
'use strict';
const { test, expect }           = require('../fixtures/eyes.fixture');
const { LoginPage }              = require('../pages/LoginPage');
const { AddEmployeePage }        = require('../pages/AddEmployeePage');
const { EmployeeListPage }       = require('../pages/EmployeeListPage');
const { ScreenshotHelper }       = require('../helpers/screenshot.helper');
const { CREDENTIALS, TEST_EMPLOYEE } = require('../data/testData');

test.describe('SCRUM-T35 | Verify role-based access control for User Login to OrangeHRM Application', () => {

  test.beforeEach(async ({ page }) => {
    // Start each test with a clean session
    await page.context().clearCookies();
  });

  test('Verify role-based access control for User Login to OrangeHRM Application', async ({ page, eyes }, testInfo) => {
    const sh        = new ScreenshotHelper(page, testInfo, eyes);
    const loginPage = new LoginPage(page);

    await sh.step('Log in as Admin and access Employee List', async () => {
      await loginPage.login(CREDENTIALS.admin.username, CREDENTIALS.admin.password);
      await page.goto('/web/index.php/pim/viewEmployeeList');
      await expect(page).toHaveURL(/viewEmployeeList/, { timeout: 15000 });
      await expect(page.locator('.oxd-table')).toBeVisible();
    });

    await sh.step('Verify Admin can access Add Employee form', async () => {
      await page.goto('/web/index.php/pim/addEmployee');
      await expect(page).toHaveURL(/addEmployee/);
      await expect(page.locator('input[name="firstName"]')).toBeVisible();
    });

    await sh.step('Clear session cookies to simulate unauthenticated user', async () => {
      await page.context().clearCookies();
    });

    await sh.step('Verify unauthenticated access to PIM redirects to Login', async () => {
      await page.goto('/web/index.php/pim/addEmployee');
      await expect(page).toHaveURL(/auth\/login/, { timeout: 10000 });
      await expect(page.locator('input[name="username"]')).toBeVisible();
    });
  });

});
