// =============================================================================
// Zephyr Test Case : SCRUM-T37
// Title            : Verify mandatory fields are enforced for User Login to OrangeHRM Application
// Priority         : Normal
// Labels           : validation, negative, required-fields, ep-empty
// Steps from Zephyr:
//   1. [Pre-condition] User is logged in as Admin.
//   2. Navigate to the User Login to OrangeHRM Application page or form.
//   3. Leave the First Name field completely empty (do not enter any value).
//   4. Leave the Last Name field completely empty (do not enter any value).
//   5. Leave any other mandatory fields empty.
//   6. Click the Save / Submit button without filling any required fields.
//   7. Observe all inline validation messages that appear below each empty field.
//   8. Verify the form does NOT submit (URL remains on the form page).
//   9. Verify the First Name field shows an error message (e.g. &quot;Required&quot;).
//   10. Verify the Last Name field shows an error message (e.g. &quot;Required&quot;).
// =============================================================================
// Generated by  : scripts/generate-playwright.js
// Application   : OrangeHRM — https://opensource-demo.orangehrmlive.com
// Module        : PIM → Add Employee
// Credentials   : Admin / admin123
// =============================================================================
'use strict';
const { test, expect }           = require('../fixtures/eyes.fixture');
const { LoginPage }              = require('../pages/LoginPage');
const { AddEmployeePage }        = require('../pages/AddEmployeePage');
const { EmployeeListPage }       = require('../pages/EmployeeListPage');
const { ScreenshotHelper }       = require('../helpers/screenshot.helper');
const { CREDENTIALS, TEST_EMPLOYEE } = require('../data/testData');

test.describe('SCRUM-T37 | Verify mandatory fields are enforced for User Login to OrangeHRM Application', () => {

  test.beforeEach(async ({ page }) => {
    // Start each test with a clean session
    await page.context().clearCookies();
  });

  test('Verify mandatory fields are enforced for User Login to OrangeHRM Application', async ({ page, eyes }, testInfo) => {
    const sh              = new ScreenshotHelper(page, testInfo, eyes);
    const loginPage       = new LoginPage(page);
    const addEmployeePage = new AddEmployeePage(page);

    await sh.step('Log in as HR Admin', async () => {
      await loginPage.login(CREDENTIALS.admin.username, CREDENTIALS.admin.password);
    });

    await sh.step('Open Add Employee form', async () => {
      await addEmployeePage.navigate();
    });

    await sh.step('Clear all required fields (First Name, Last Name)', async () => {
      await addEmployeePage.firstNameInput.clear();
      await addEmployeePage.lastNameInput.clear();
    });

    await sh.step('Attempt to submit with empty required fields', async () => {
      await addEmployeePage.save();
    });

    await sh.step('Verify inline validation error messages appear', async () => {
      await expect(addEmployeePage.validationErrors.first()).toBeVisible({ timeout: 5000 });
      const errorCount = await addEmployeePage.validationErrors.count();
      expect(errorCount).toBeGreaterThanOrEqual(1);
      await expect(page).not.toHaveURL(/viewPersonalDetails/);
    });
  });

});
