// =============================================================================
// Zephyr Test Case : SCRUM-T42
// Title            : Verify UI feedback messages are correct for User Login to OrangeHRM Application
// Priority         : Normal
// Labels           : ui, usability, feedback, use-case
// Steps from Zephyr:
//   1. [Pre-condition] User is logged in as Admin. Navigate to User Login to OrangeHRM Application form.
//   2. [Positive] Complete a successful User Login to OrangeHRM Application with valid data (First Name: &quot;UITest&quot;, Last Name: &quot;User&quot;).
//   3. Verify the success toast / notification appears and reads &quot;Successfully Saved&quot; (or equivalent).
//   4. Verify the success message is visible for the expected duration, then disappears or has a dismiss option.
//   5. Verify the success message is free from spelling mistakes and grammatical errors.
//   6. [Negative] Submit the form with empty required fields.
//   7. Verify field-level error messages appear in red / highlighted styling.
//   8. Verify error messages are actionable (e.g. &quot;First Name is required&quot; not just &quot;Error&quot;).
//   9. [Recovery] Fill valid data after seeing errors and re-submit.
//   10. Verify the form recovers cleanly, error messages clear, and success is shown.
// =============================================================================
// Generated by  : scripts/generate-playwright.js
// Application   : OrangeHRM — https://opensource-demo.orangehrmlive.com
// Module        : PIM → Add Employee
// Credentials   : Admin / admin123
// =============================================================================
'use strict';
const { test, expect }           = require('@playwright/test');
const { LoginPage }              = require('../pages/LoginPage');
const { AddEmployeePage }        = require('../pages/AddEmployeePage');
const { EmployeeListPage }       = require('../pages/EmployeeListPage');
const { ScreenshotHelper }       = require('../helpers/screenshot.helper');
const { CREDENTIALS, TEST_EMPLOYEE } = require('../data/testData');

test.describe('SCRUM-T42 | Verify UI feedback messages are correct for User Login to OrangeHRM Application', () => {

  test.beforeEach(async ({ page }) => {
    // Start each test with a clean session
    await page.context().clearCookies();
  });

  test('Verify UI feedback messages are correct for User Login to OrangeHRM Application', async ({ page }, testInfo) => {
    const sh              = new ScreenshotHelper(page, testInfo);
    const loginPage       = new LoginPage(page);
    const addEmployeePage = new AddEmployeePage(page);

    await sh.step('Log in as HR Admin', async () => {
      await loginPage.login(CREDENTIALS.admin.username, CREDENTIALS.admin.password);
    });

    await sh.step('Submit valid employee to trigger success feedback', async () => {
      await addEmployeePage.navigate();
      await addEmployeePage.fillEmployee({ firstName: 'UIFeedback', lastName: 'Success' });
      await addEmployeePage.save();
      await expect(page).toHaveURL(/viewPersonalDetails/, { timeout: 15000 });
    });

    await sh.step('Verify success state — Personal Details page is visible', async () => {
      await expect(page.locator('h6.oxd-text').first()).toBeVisible();
    });

    await sh.step('Submit empty form to trigger validation error feedback', async () => {
      await addEmployeePage.navigate();
      await addEmployeePage.firstNameInput.clear();
      await addEmployeePage.lastNameInput.clear();
      await addEmployeePage.save();
    });

    await sh.step('Verify validation error messages are visible', async () => {
      await expect(addEmployeePage.validationErrors.first()).toBeVisible({ timeout: 5000 });
    });
  });

});
