// =============================================================================
// Zephyr Test Case : SCRUM-T39
// Title            : Verify boundary values are handled correctly for User Login to OrangeHRM Application
// Priority         : Normal
// Labels           : boundary, edge-case, bva
// Steps from Zephyr:
//   1. [Pre-condition] User is logged in as Admin. Navigate to User Login to OrangeHRM Application form.
//   2. [BVA-1] Enter minimum boundary value: single character &quot;A&quot; in First Name and &quot;B&quot; in Last Name. Submit and verify the form accepts it.
//   3. [BVA-2] Enter Min+1 boundary value: two characters &quot;AB&quot; in First Name. Submit and verify acceptance.
//   4. [BVA-3] Navigate back and enter Max-1 boundary value: 49-character string in First Name. Submit and verify acceptance.
//   5. [BVA-4] Navigate back and enter the exact maximum boundary: 50-character string in First Name. Submit and verify acceptance.
//   6. [BVA-5] Navigate back and enter Max+1 boundary: 51-character string in First Name. Submit and verify rejection with error message.
//   7. Record actual system behaviour for each boundary point in a table.
//   8. Verify that accepted boundary values are correctly persisted and displayed.
// =============================================================================
// Generated by  : scripts/generate-playwright.js
// Application   : OrangeHRM — https://opensource-demo.orangehrmlive.com
// Module        : PIM → Add Employee
// Credentials   : Admin / admin123
// =============================================================================
'use strict';
const { test, expect }           = require('../fixtures/eyes.fixture');
const { LoginPage }              = require('../pages/LoginPage');
const { AddEmployeePage }        = require('../pages/AddEmployeePage');
const { EmployeeListPage }       = require('../pages/EmployeeListPage');
const { ScreenshotHelper }       = require('../helpers/screenshot.helper');
const { CREDENTIALS, TEST_EMPLOYEE } = require('../data/testData');

test.describe('SCRUM-T39 | Verify boundary values are handled correctly for User Login to OrangeHRM Application', () => {

  test.beforeEach(async ({ page }) => {
    // Start each test with a clean session
    await page.context().clearCookies();
  });

  test('Verify boundary values are handled correctly for User Login to OrangeHRM Application', async ({ page, eyes }, testInfo) => {
    const sh              = new ScreenshotHelper(page, testInfo, eyes);
    const loginPage       = new LoginPage(page);
    const addEmployeePage = new AddEmployeePage(page);

    await sh.step('Log in as HR Admin', async () => {
      await loginPage.login(CREDENTIALS.admin.username, CREDENTIALS.admin.password);
    });

    await sh.step('Test minimum boundary — single character names (A, B)', async () => {
      await addEmployeePage.navigate();
      await addEmployeePage.fillEmployee({ firstName: 'A', lastName: 'B' });
      await addEmployeePage.save();
      await expect(page).toHaveURL(/viewPersonalDetails|addEmployee/, { timeout: 10000 });
    });

    await sh.step('Test maximum boundary — 50-character names', async () => {
      await addEmployeePage.navigate();
      await addEmployeePage.fillEmployee({
        firstName: 'A'.repeat(50),
        lastName:  'B'.repeat(50)
      });
      await addEmployeePage.save();
      await page.waitForLoadState('networkidle');
      expect(page.url()).not.toMatch(/error|exception/i);
    });

    await sh.step('Test over-maximum boundary — 101-character names', async () => {
      await addEmployeePage.navigate();
      await addEmployeePage.fillEmployee({
        firstName: 'X'.repeat(101),
        lastName:  'Y'.repeat(101)
      });
      await addEmployeePage.save();
      await page.waitForLoadState('networkidle');
      expect(page.url()).not.toMatch(/error|exception/i);
    });
  });

});
